### ISSUE TITLE
Instructions on how to use?

### ISSUE THREAD

**Issue by HanYangZhao** [caillonantoine/ddsp-recode#1]
Hi,

I saw the demo on Youtube and thought it was really cool. I was wondering if you could provide some instructions on how to use this repo so I can try myself as well. I am familiar with pytorch, TouchOSC and PD, but I'm not sure how the code is organized in this repo.

Thanks

**Comment by caillonantoine** [comment]
Hi,

sorry for the late answer, but unfortunately my implementation is no longer compatible with the new versions of libtorch. I'm currently working on an up to date version, I will keep you updated !

Cheers

**Comment by HanYangZhao** [comment]
ah ok thank you

**Comment by caillonantoine** [comment]
Hi,

Just to late you know I've re-written the entire code and built a new Pd external, so everything works now ! (tested on macos + linux)

Cheers
